name: staging-webservice

on:
  push:
    branches:
      - dev
      - "**webservice**"
      - "**cicd**"

jobs:
  webservice:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      docker-profile: --profile webservice
      environment: staging
    secrets: inherit
    # secrets:
    #   dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
    #   dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    #   ssh-password: ${{ secrets.SSH_PASSWORD }}
    #   ssh-username: ${{ secrets.SSH_USERNAME }}
    #   ssh-host: ${{ secrets.SSH_HOST }}
