# Configure staging pipeline for website

name: staging-website

on:
  push:
    branches:
      - dev
      - "**website**"

jobs:
  website:
    uses: holstt/inciport/.github/workflows/build-test-deploy.yml@dev
    with:
      docker-profile: --profile website
      environment: staging
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      ssh-password: ${{ secrets.SSH_PASSWORD }}
      ssh-username: ${{ secrets.SSH_USERNAME }}
      ssh-host: ${{ secrets.SSH_HOST }}
