# Configure staging pipeline for website

name: staging-website

on:
  push:
    branches:
      - dev
      - "**website**"

jobs:
  website:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      project_dir: inciport-website
      build_args: |
        FOLDER=inciport-website
    secrets: inherit
