# Configure staging pipeline for website

name: staging-website

on:
  push:
    branches:
      - dev
      - "**website**"
      - "**cicd**"

jobs:
  website:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      docker-profile: --profile website
      environment: staging
    secrets: inherit
    # secrets:
    #   dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
    #   dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    #   ssh-password: ${{ secrets.SSH_PASSWORD }}
    #   ssh-username: ${{ secrets.SSH_USERNAME }}
    #   ssh-host: ${{ secrets.SSH_HOST }}
