name: staging-webservice

on:
  push:
    branches:
      - dev
      - "**webservice**"
      - "**cicd**"

jobs:
  webservice:
    uses: ./.github/workflows/build-test-deploy.yml
    with:
      project_dir: inciport-webservice
      build_args: |
        FOLDER=inciport-webservice
        SLN=InciportWebService
        P1=Api
        P2=Application
        P3=Domain
        P4=Data
        P5=UnitTests
        P6=IntegrationTests
        START_P=Api

    secrets: inherit
